In [2]:
import numpy as np

In [4]:
t = np.ones((4,3,2))

In [6]:
t.shape

(4, 3, 2)

In [11]:
t[0][0][1] = 9

In [12]:
t

array([[[1., 9.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [13]:
t[0][0]

array([1., 9.])

In [15]:
t[0]

array([[1., 9.],
       [1., 1.],
       [1., 1.]])

In [37]:
list((np.random.random((2,2)) for _ in range(8)))

[array([[0.44898224, 0.51194799],
        [0.42317436, 0.8422208 ]]),
 array([[0.93725761, 0.64406025],
        [0.50454222, 0.71488799]]),
 array([[0.29118942, 0.63558624],
        [0.73221129, 0.53369476]]),
 array([[0.84752817, 0.11442131],
        [0.5908797 , 0.77101322]]),
 array([[0.93240206, 0.86402155],
        [0.14216254, 0.34476342]]),
 array([[0.44535216, 0.48568198],
        [0.96889881, 0.38697736]]),
 array([[0.74097098, 0.86659066],
        [0.68619108, 0.76901484]]),
 array([[0.80821599, 0.60692958],
        [0.03827036, 0.08250543]])]

In [34]:
a

array([[0.43374114, 0.00328858],
       [0.80881161, 0.91965161]])

In [38]:
np.random.random?

Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.
Type:      builtin_function_or_method
